export const data = [
  { id: '1', text: 'Lorem Ipsum' },
  { id: '2', text: 'Random Text' },
  { id: '3', text: 'JavaScript Rocks' },
  { id: '4', text: 'React Native Magic' },
  { id: '5', text: 'Coding is Fun' },
  { id: '6', text: 'Hello World' },
  { id: '7', text: 'Coffee Break' },
  { id: '8', text: 'Tech Innovation' },
  { id: '9', text: 'Mobile Development' },
  { id: '10', text: 'Open Source Love' },
  { id: '11', text: 'Data Science Wonders' },
  { id: '12', text: 'User Experience Matters' },
  { id: '13', text: 'Web Development Joy' },
  { id: '14', text: 'Code and Create' },
  { id: '15', text: 'Digital Art Inspiration' },
  { id: '16', text: 'Design Thinking' },
  { id: '17', text: 'Testing in Production' },
  { id: '18', text: 'Agile Mindset' },
  { id: '19', text: 'Serverless Awesomeness' },
  { id: '20', text: 'Full Stack Dreams' },
];
